#-------------------公共配置-----------------------
spring:
  profiles:
    active: test  #默认使用配置
  http:        
    encoding:  #http请求响应字符集配置
      charset: UTF-8  
      enabled: true
      force: true
#  cache: #缓存相关配置
#    type: ehcache
#    ehcache:
#      config: classpath:ehcache.xml

mybatis:
  mapperLocations: classpath:mapper/*.xml   #指定mapper 文件路径   

server:
  servlet:
    context-path: /imConsumer #工程项目名称

logging:
  level:
    com.zjrc.sxzz.dao: DEBUG

  
---    
#---------------测试配置
spring:
  profiles: test
  datasource: #数据库配置
    url: jdbc:mysql://20.21.1.92:3306/fjzl_tz?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sxzz@rc2015
    driver-class-name: com.mysql.jdbc.Driver  
    type: com.alibaba.druid.pool.DruidDataSource #指定数据源
  
server:
  port: 8082 #端口号配置
  
---
#---------------本地数据库配置
spring:
  profiles: local
  datasource: #数据库配置
    url: jdbc:mysql://localhost:3306/fjzl_tz?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver  
    type: com.alibaba.druid.pool.DruidDataSource #指定数据源
    
server:
  port: 8084 #端口号配置  


  
    


    
    